<a href="https://colab.research.google.com/github/prithwis/FDS/blob/main/Data_Cleaning_Simple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![CC-BY-SA](https://licensebuttons.net/l/by-sa/3.0/88x31.png)<br>
<hr>

![alt text](https://github.com/Praxis-QR/RDWH/raw/main/images/YantraJaalBanner.png)<br>


<hr>

[Prithwis Mukerjee](http://www.linkedin.com/in/prithwis)<br>

#Data Cleaning - Simple
https://www.w3schools.com/python/pandas/pandas_cleaning.asp

In [1]:
!wget -q -O data.csv https://raw.githubusercontent.com/Praxis-QR/FDS/main/data/w3s-datacleaning2.csv

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data.csv')
df

    Unnamed: 0  Duration         Date   Pulse  Maxpulse  Calories
0            0        60  '2020/12/01'    110       130     409.1
1            1        60  '2020/12/02'    117       145     479.0
2            2        60  '2020/12/03'    103       135     340.0
3            3        45  '2020/12/04'    109       175     282.4
4            4        45  '2020/12/05'    117       148     406.0
5            5        60  '2020/12/06'    102       127     300.0
6            6        60  '2020/12/07'    110       136     374.0
7            7       450  '2020/12/08'    104       134     253.3
8            8        30  '2020/12/09'    109       133     195.1
9            9        60  '2020/12/10'     98       124     269.0
10          10        60  '2020/12/11'    103       147     329.3
11          11        60  '2020/12/12'    100       120     250.7
12          12        60  '2020/12/12'    100       120     250.7
13          13        60  '2020/12/13'    106       128     345.3
14          14        60  '2020/12/14'    104       132     379.3
15          15        60  '2020/12/15'     98       123     275.0
16          16        60  '2020/12/16'     98       120     215.2
17          17        60  '2020/12/17'    100       120     300.0
18          18        45  '2020/12/18'     90       112       NaN
19          19        60  '2020/12/19'    103       123     323.0
20          20        45  '2020/12/20'     97       125     243.0
21          21        60  '2020/12/21'    108       131     364.2
22          22        45           NaN    100       119     282.0
23          23        60  '2020/12/23'    130       101     300.0
24          24        45  '2020/12/24'    105       132     246.0
25          25        60  '2020/12/25'    102       126     334.5
26          26        60    2020/12/26    100       120     250.0
27          27        60  '2020/12/27'     92       118     241.0
28          28        60  '2020/12/28'    103       132       NaN
29          29        60  '2020/12/29'    100       132     280.0
30          30        60  '2020/12/30'    102       129     380.3
31          31        60  '2020/12/31'     92       115     243.0

In [4]:
#Dropping columns in a DataFrame
df.drop(['Unnamed: 0'], axis = 1, inplace=True)
df

    Duration         Date   Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    2020/12/26    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [5]:
#Drop rows with blanks
df2a = df.dropna()
df2a

    Duration         Date   Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    2020/12/26    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [6]:
#Replace null values with computed values
x = df["Calories"].median()
df2b = df2a
df2b["Calories"].fillna(x, inplace = True)
df2b

/tmp/ipykernel_8663/2829594658.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2b["Calories"].fillna(x, inplace = True)
/tmp/ipykernel_8663/2829594658.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2b["Calories"].fillna(x, inplace = True)

    Duration         Date   Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60    2020/12/26    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [7]:
df2b.info()

<class 'pandas.core.frame.DataFrame'>
Index: 29 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  29 non-null     int64
 1   Date      29 non-null     object
 2   Pulse     29 non-null     int64
 3   Maxpulse  29 non-null     int64
 4   Calories  29 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [8]:
df2b.columns                                               # Note name of column Date

Index(['Duration', 'Date ', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [9]:
#Fixing Date
df3 = df2b
df3['Date'] = pd.to_datetime(df3['Date'])
df3

KeyError: 'Date'

In [10]:
df3 = df2b
df3.columns

Index(['Duration', 'Date ', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [11]:
df3.rename(columns = {'Date ':'Date'}, inplace = True)

/tmp/ipykernel_8663/1010930068.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3.rename(columns = {'Date ':'Date'}, inplace = True)

In [12]:
df3['Date'] = pd.to_datetime(df3['Date'])
df3

ValueError: time data "2020/12/26" doesn't match format "'%Y/%m/%d'", at position 24. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [13]:
df3['Date'] = pd.to_datetime(df3['Date'], format='mixed')
df3

/tmp/ipykernel_8663/387179766.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['Date'] = pd.to_datetime(df3['Date'], format='mixed')

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [14]:
#Remove Row 22
#df3.dropna(subset=['Date'], inplace = True)
#df3

#No Headers

In [15]:
!wget -O OfficeSales.csv https://raw.githubusercontent.com/Praxis-QR/FDS/main/data/OfficeSupplies_NoHeader.csv

--2026-08-31 06:24:45--  https://raw.githubusercontent.com/Praxis-QR/FDS/main/data/OfficeSupplies_NoHeader.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1700 (1.7K) [text/plain]
Saving to: ‘OfficeSales.csv’

OfficeSales.csv     100%[===================>]   1.66K  --.-KB/s    in 0s

2026-08-31 06:24:45 (27.0 MB/s) - ‘OfficeSales.csv’ saved [1700/1700]

In [16]:
#Error
dfOS = pd.read_csv('/content/OfficeSales.csv')
dfOS.head()

    4-Jul-2014     East  Richard  Pen Set  62   4.99
0  12-Jul-2014     East     Nick   Binder  29   1.99
1  21-Jul-2014  Central   Morgan  Pen Set  55  12.49
2  29-Jul-2014     East    Susan   Binder  81  19.99
3   7-Aug-2014  Central  Matthew  Pen Set  42  23.95
4  15-Aug-2014     East  Richard   Pencil  35   4.99

In [17]:
#Inconvenient
dfOS = pd.read_csv('/content/OfficeSales.csv', header=None)
dfOS.head()

             0        1        2        3   4      5
0   4-Jul-2014     East  Richard  Pen Set  62   4.99
1  12-Jul-2014     East     Nick   Binder  29   1.99
2  21-Jul-2014  Central   Morgan  Pen Set  55  12.49
3  29-Jul-2014     East    Susan   Binder  81  19.99
4   7-Aug-2014  Central  Matthew  Pen Set  42  23.95

In [18]:
#Correct
colNames = ['OrderDate','Region','Rep','Item','Units','Unit Price']
dfOS = pd.read_csv('/content/OfficeSales.csv',names=colNames)
dfOS.head()

     OrderDate   Region      Rep     Item  Units  Unit Price
0   4-Jul-2014     East  Richard  Pen Set     62        4.99
1  12-Jul-2014     East     Nick   Binder     29        1.99
2  21-Jul-2014  Central   Morgan  Pen Set     55       12.49
3  29-Jul-2014     East    Susan   Binder     81       19.99
4   7-Aug-2014  Central  Matthew  Pen Set     42       23.95

#ChronoTantra | ChronoYantra | ChronoMantra | ChronoSutra
 [Finished scrolling? Now try reading a book. ](http://chronos.yantrajaal.com) <br>

[![More Information](https://raw.githubusercontent.com/prithwis/parashar21/refs/heads/main/images/CTYMS-Colab-Footer.png)](https://chronos.yantrajaal.com)