<a href="https://colab.research.google.com/github/prithwis/FDS/blob/main/FDS_Data36_Pandas_Tutorial_Starter_Pack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![alt text](https://github.com/Praxis-QR/RDWH/raw/main/images/YantraJaalBanner.png)<br>


<hr>

[Prithwis Mukerjee](http://www.linkedin.com/in/prithwis)<br>

In [1]:
from datetime import datetime
import pytz
print('Tested at  ',datetime.now(pytz.timezone('Asia/Kolkata')))

Tested at   2026-08-31 11:26:06.401683+05:30

##Reference<br>
[Data36 Tutorial 1](https://data36.com/pandas-tutorial-1-basics-reading-data-files-dataframes-data-selection/)<br>
[Data36 Tutorial 2](https://data36.com/pandas-tutorial-2-aggregation-and-grouping/)

In [2]:
import numpy as np
import pandas as pd

#Loading Data

## Pandas Tutorial Data Set

### Option 1 : download and read

In [3]:
!wget -O Tutorial.csv -q  https://raw.githubusercontent.com/Praxis-QR/FDS/main/data/pandas_tutorial_read.csv

In [4]:
#!head Tutorial.csv

In [5]:
df_ArticleRead = pd.read_csv('Tutorial.csv', delimiter=';', header=None)
df_ArticleRead.head()

                     0     1          2           3        4              5
0  2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
1  2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2  2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3  2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4  2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America

In [6]:
colNames = ['my_datetime', 'event', 'country', 'user_id', 'source', 'topic']
df_ArticleRead = pd.read_csv('Tutorial.csv', delimiter=';', names = colNames)
df_ArticleRead.head()

           my_datetime event    country     user_id   source          topic
0  2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
1  2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2  2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3  2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4  2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America

### Option 2 : read direct from URL

In [7]:
dataURL = 'https://raw.githubusercontent.com/Praxis-QR/FDS/main/data/pandas_tutorial_read.csv'
colNames = ['my_datetime', 'event', 'country', 'user_id', 'source', 'topic']
df_ArticleRead = pd.read_csv(dataURL, delimiter=';', names = colNames )
df_ArticleRead.head()

           my_datetime event    country     user_id   source          topic
0  2018-01-01 00:01:01  read  country_7  2458151261      SEO  North America
1  2018-01-01 00:03:20  read  country_7  2458151262      SEO  South America
2  2018-01-01 00:04:01  read  country_7  2458151263  AdWords         Africa
3  2018-01-01 00:04:02  read  country_7  2458151264  AdWords         Europe
4  2018-01-01 00:05:03  read  country_8  2458151265   Reddit  North America

## Zoo Data Set

In [8]:
#locate at https://drive.google.com/file/d/1LHrgbUoNrI2HG3bktN-Ak63Vw4ywW-XY/view?usp=sharing
#!gdown https://drive.google.com/uc?id=1LHrgbUoNrI2HG3bktN-Ak63Vw4ywW-XY
dataURL = 'https://raw.githubusercontent.com/Praxis-QR/FDS/main/data/zoo.csv'
dfZoo = pd.read_csv(dataURL)

In [9]:
dfZoo.head(5)

     animal  uniq_id  water_need
0  elephant     1001         500
1  elephant     1002         600
2  elephant     1003         550
3     tiger     1004         300
4     tiger     1005         320

#ChronoTantra | ChronoYantra | ChronoMantra | ChronoSutra
 [Finished scrolling? Now try reading a book. ](http://chronos.yantrajaal.com) <br>

[![More Information](https://raw.githubusercontent.com/prithwis/parashar21/refs/heads/main/images/CTYMS-Colab-Footer.png)](https://chronos.yantrajaal.com)