<a href="https://colab.research.google.com/github/prithwis/FDS/blob/main/FDS_OfficeSales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![CC-BY-SA](https://licensebuttons.net/l/by-sa/3.0/88x31.png)<br>
<hr>

![alt text](https://github.com/Praxis-QR/RDWH/raw/main/images/YantraJaalBanner.png)<br>


<hr>

[Prithwis Mukerjee](http://www.linkedin.com/in/prithwis)<br>

Tutorial is [here](https://www.atmosera.com/blog/using-pandas-to-analyze-sales-data/) <br>

In [1]:
from datetime import datetime
import pytz
print("\033[1m"+'ॐ श्री गणेशाय नमः'+"\033[0m")
print(datetime.now(pytz.timezone('Asia/Calcutta')))

ॐ श्री गणेशाय नमः
2026-08-31 11:17:44.990372+05:30

#Get data

You can either use wget to pull data directly from the website into the VM or you can first download the data into your local laptop and then upload it in the colab VM. <br>

You should NOT use BOTH options

In [2]:
# http://www.superdatascience.com/wp-content/uploads/2015/06/OfficeSupplies.csv
#!wget -O OfficeSupplies.csv 'https://drive.google.com/uc?export=download&id=15iYK-17rF-b4g4Grk48RRME2TjR6yBXk'
!wget -O OfficeSupplies.csv -q 'https://raw.githubusercontent.com/Praxis-QR/FDS/main/data/OfficeSupplies.csv'

In [3]:
!ls

OfficeSupplies.csv  sample_data

#Imports

In [4]:
import pandas as pd
import numpy as np

#Read Data

In [5]:
# Data provided by https://www.superdatascience.com/
df = pd.read_csv("OfficeSupplies.csv")

#General Analysis

In [6]:
df.shape

(43, 6)

In [7]:
df.dtypes

OrderDate      object
Region         object
Rep            object
Item           object
Units           int64
Unit Price    float64
dtype: object

In [8]:
df.head()

     OrderDate   Region      Rep     Item  Units  Unit Price
0   4-Jul-2014     East  Richard  Pen Set     62        4.99
1  12-Jul-2014     East     Nick   Binder     29        1.99
2  21-Jul-2014  Central   Morgan  Pen Set     55       12.49
3  29-Jul-2014     East    Susan   Binder     81       19.99
4   7-Aug-2014  Central  Matthew  Pen Set     42       23.95

In [9]:
df.describe()

           Units  Unit Price
count  43.000000   43.000000
mean   49.325581   20.308605
std    30.078248   47.345118
min     2.000000    1.290000
25%    27.500000    3.990000
50%    53.000000    4.990000
75%    74.500000   17.990000
max    96.000000  275.000000

#Any null values in the dataset?

In [10]:
#df.isnull().values.any()
df.isnull().values.any()

np.False_

#Reps who sold the most units

In [11]:
#df.groupby(["Rep"]).sum().sort_values("Units", ascending=False)
#df.groupby(["Rep"]).sum().sort_values("Units")
#df.groupby(["Rep"]).sum()
df.groupby(["Rep"]).sum(numeric_only=True)
#df.groupby(["Rep"]).mean()

         Units  Unit Price
Rep
Alex       281       39.95
Bill       213       40.55
James      142      299.97
Matthew    193      173.93
Morgan     173       26.47
Nick       125        6.98
Rachel     183       10.26
Richard    396       55.92
Smith      156      141.29
Susan      170       55.97
Thomas      89       21.98

#Add a new column to our dataset

In [12]:
df["Value"] = df["Units"] * df["Unit Price"]
df.head()

     OrderDate   Region      Rep     Item  Units  Unit Price    Value
0   4-Jul-2014     East  Richard  Pen Set     62        4.99   309.38
1  12-Jul-2014     East     Nick   Binder     29        1.99    57.71
2  21-Jul-2014  Central   Morgan  Pen Set     55       12.49   686.95
3  29-Jul-2014     East    Susan   Binder     81       19.99  1619.19
4   7-Aug-2014  Central  Matthew  Pen Set     42       23.95  1005.90

#Pivot Table

In [13]:
pd.pivot_table(df[['Region','Item','Units','Value']],index="Region", columns="Item", values = 'Value',aggfunc="sum")

Item      Binder   Desk      Pen  Pen Set   Pencil
Region
Central  5762.63  875.0   539.73  2421.39  1540.32
East     2535.66    NaN  1354.25  1748.48   363.70
West     1279.36  825.0   151.24      NaN   231.12

In [14]:
pd.pivot_table(df[['Region','Item','Units','Value']],index="Region", columns="Item", values = 'Value', margins =True,aggfunc="sum")

Item      Binder    Desk      Pen  Pen Set   Pencil       All
Region
Central  5762.63   875.0   539.73  2421.39  1540.32  11139.07
East     2535.66     NaN  1354.25  1748.48   363.70   6002.09
West     1279.36   825.0   151.24      NaN   231.12   2486.72
All      9577.65  1700.0  2045.22  4169.87  2135.14  19627.88

#Additional analysis

In [15]:
#
# Who sold the most?
#
#f.groupby("Rep").sum().sort_values("Total Price", ascending=False).head()
df.groupby("Rep").sum(numeric_only=True).sort_values("Value", ascending=False).head()
#df.groupby("Rep").sum()[['Units','Total Price']].sort_values("Total Price", ascending=False).head()

         Units  Unit Price    Value
Rep
Matthew    193      173.93  3109.44
Susan      170       55.97  3102.30
Alex       281       39.95  2812.19
Richard    396       55.92  2363.04
Bill       213       40.55  1749.87

In [16]:
#
# Who sold the most?
#
#df.groupby("Rep").sum().sort_values("Total Price", ascending=False).head()
df.groupby("Rep").sum()[['Units','Value']].sort_values("Value", ascending=False).head()

         Units    Value
Rep
Matthew    193  3109.44
Susan      170  3102.30
Alex       281  2812.19
Richard    396  2363.04
Bill       213  1749.87

In [17]:
#
# Who sold most units
#
df.groupby("Rep").sum()[['Units','Value']].sort_values("Units", ascending=False).head()

         Units    Value
Rep
Richard    396  2363.04
Alex       281  2812.19
Bill       213  1749.87
Matthew    193  3109.44
Rachel     183   438.37

In [18]:
#
# Which region sold the most?
#
df.groupby("Region")[['Units','Value']].sum()

         Units     Value
Region
Central   1199  11139.07
East       691   6002.09
West       231   2486.72

In [19]:
#
# What item sold the most
#
df.groupby("Item")[['Units','Value']].sum()

         Units    Value
Item
Binder     722  9577.65
Desk        10  1700.00
Pen        278  2045.22
Pen Set    395  4169.87
Pencil     716  2135.14

In [20]:
#
# who sold the most in each region
#
group = df.groupby(["Region","Rep"]).sum()
total_price = group["Value"].groupby(level=0, group_keys=False)
total_price.nlargest(5)

Region   Rep
Central  Matthew    3109.44
         Alex       2812.19
         Bill       1749.87
         Smith      1641.43
         Morgan     1387.77
East     Susan      3102.30
         Richard    2363.04
         Nick        536.75
West     James      1283.61
         Thomas     1203.11
Name: Value, dtype: float64

In [21]:
df.groupby(["Region","Rep"])[['Units','Value']].sum()

                 Units    Value
Region  Rep
Central Alex       281  2812.19
        Bill       213  1749.87
        Matthew    193  3109.44
        Morgan     173  1387.77
        Rachel     183   438.37
        Smith      156  1641.43
East    Nick       125   536.75
        Richard    396  2363.04
        Susan      170  3102.30
West    James      142  1283.61
        Thomas      89  1203.11

#ChronoTantra | ChronoYantra | ChronoMantra | ChronoSutra
 [Finished scrolling? Now try reading a book. ](http://chronos.yantrajaal.com) <br>

[![More Information](https://raw.githubusercontent.com/prithwis/parashar21/refs/heads/main/images/CTYMS-Colab-Footer.png)](https://chronos.yantrajaal.com)